version: '3.7'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins

  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    container_name: prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "9092:3000"
    container_name: grafana
    depends_on:
      - prometheus

volumes:
  jenkins_home:
